name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Backend - Build Docker image
        run: docker build ./backend -t backend:test

      - name: Frontend - Build Docker image
        run: docker build ./frontend -t frontend:test
