name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: example
          POSTGRES_PASSWORD: example
          POSTGRES_DB: exampledb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend
        run: docker build -t backend ./backend

      - name: Build frontend
        run: docker build -t frontend ./frontend

      # - name: Run backend tests
      #   run: docker run --rm backend npm test

  # Exemple de job de déploiement (je n'ai pas de server)
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to server
  #       run:
